use_frameworks!

platform :ios, '8.0'

target 'testPod_Example' do
  pod 'testPod', :path => '../'

  target 'testPod_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
